services:
  - type: web
    name: mtc-chord-api
    env: python
    buildCommand: pip install Cython==3.0.10 numpy==1.26.4 && pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --timeout 300 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
